### PR TITLE
Add test & update Grafana dashboard for Erlang distribution buffer busy limit, a.k.a. zdbbl

### LINKED ISSUE #39: Metrics missing for distribution buffer busy limit - zdbbl
Now that https://github.com/erlang/otp/pull/2270 & https://github.com/deadtrickster/prometheus.erl/pull/94 have been merged and released, we want to expose and visualise the distribution buffer busy limit (a.k.a. [zdbbl](https://erlang.org/doc/man/erl.html#+zdbbl)).

The goal is to be able to measure how busy a particular distribution link is, so that users of RabbitMQ would know when increasing the inter-node communication buffer size would be beneficial. When implemented, this feature will be a good companion to [RabbitMQ Runtime Tuning - Inter-node Communication Buffer Size](https://www.rabbitmq.com/runtime.html#distribution-buffer).

This was created part of https://github.com/rabbitmq/tgir/pull/9. The expectation is that one of the viewers will implement this feature, by following the video. Hopefully, this will inspire others to contribute features & fixes to RabbitMQ 🙌🏻

[Thanks Matt E for reminding us about this outstanding issue](https://groups.google.com/forum/#!topic/rabbitmq-users/F8f26MaFSqY/discussion)

### PR DESCRIPTION
**Pull request by gerhard**
Since none that watched [TGIR S01E04](https://www.youtube.com/watch?v=9q-_DLfhfYg) contributed this feature, I will add the missing pieces & back-port to <kbd>v3.8.x</kbd>

This is a follow-up to #40 & it closes #39 .

### CODE REVIEW

**Comment by gerhard** [comment]
Merge & back-port after checks go green.

**Comment by gerhard** [comment]
Back-ported to <kbd>v3.8.x</kbd> via https://github.com/rabbitmq/rabbitmq-prometheus/commit/0612960036d0c0cc29eefe48de224a4db81fc5d4

**Comment by bhughes23** [comment]
How can we deploy this fix to a cluster running 3.8.2 without upgrading to 3.8.4?

**Comment by gerhard** [comment]
1. Stop RabbitMQ
2. In the `plugins` directory (`rabbitmq-diagnostics environment | grep plugins_dir`) remove `prometheus-4.4.0.ez` & add `prometheus-4.6.0.ez` (you will find this inside https://github.com/rabbitmq/rabbitmq-server/releases/download/v3.8.8/rabbitmq-server-generic-unix-3.8.8.tar.xz)
3. Restart RabbitMQ
4. Repeat for all other nodes

While the above is possible, I am not sure why you would want to mix & match components from different RabbitMQ version. We have shipped many fixes & added significant new features between v3.8.2 & v3.8.8. All release notes in one place: https://github.com/rabbitmq/rabbitmq-website/tree/live/site/release-notes

What is preventing you from upgrading to latest stable RabbitMQ v3.8.8?

**Pull request merged**
